import { DecoratedText } from "./classes/DecoratedText";
import { CardSection } from "./classes/CardSection";
import { Action } from "./classes/Action";
import { ActionResponseBuilder } from "./classes/ActionResponseBuilder";
import { AuthorizationAction } from "./classes/AuthorizationAction";
import { AuthorizationException } from "./classes/AuthorizationException";
import { ComposeActionResponseBuilder } from "./classes/ComposeActionResponseBuilder";
import { UpdateDraftActionResponseBuilder } from "./classes/UpdateDraftActionResponseBuilder";
import { UpdateDraftBodyAction } from "./classes/UpdateDraftBodyAction";
import { ButtonSet } from "./classes/ButtonSet";
import { CardAction } from "./classes/CardAction";
import { CardBuilder } from "./classes/CardBuilder";
import { CardHeader } from "./classes/CardHeader";
import { Image } from "./classes/Image";
import { ImageButton } from "./classes/ImageButton";
import { Navigation } from "./classes/Navigation";
import { Notification } from "./classes/Notification";
import { OpenLink } from "./classes/OpenLink";
import { SelectionInput } from "./classes/SelectionInput";
import { Suggestions } from "./classes/Suggestions";
import { TextButton } from "./classes/TextButton";
import { TextInput } from "./classes/TextInput";
import { TextParagraph } from "./classes/TextParagraph";
import { UniversalActionResponseBuilder } from "./classes/UniversalActionResponseBuilder";
import { ComposeEmailType } from "./enums/ComposeEmailType";
import { Icon } from "./enums/Icon";
import { ImageStyle } from "./enums/ImageStyle";
import { LoadIndicator } from "./enums/LoadIndicator";
import { NotificationType } from "./enums/NotificationType";
import { OnClose } from "./enums/OnClose";
import { OpenAs } from "./enums/OpenAs";
import { SelectionInputType } from "./enums/SelectionInputType";
import { TextButtonStyle } from "./enums/TextButtonStyle";
import { ContentType } from "./enums/ContentType";
import { UpdateDraftBodyType } from "./enums/UpdateDraftBodyType";
export declare class CardService {
    static newAction(): Action;
    static newActionResponseBuilder(): ActionResponseBuilder;
    static newAuthorizationAction(): AuthorizationAction;
    static newAuthorizationException(): AuthorizationException;
    static newComposeActionResponseBuilder(): ComposeActionResponseBuilder;
    static newDecoratedText(): DecoratedText;
    static newUpdateDraftActionResponseBuilder(): UpdateDraftActionResponseBuilder;
    static newUpdateDraftBodyAction(): UpdateDraftBodyAction;
    static newButtonSet(): ButtonSet;
    static newCardAction(): CardAction;
    static newCardBuilder(): CardBuilder;
    static newCardHeader(): CardHeader;
    static newCardSection(): CardSection;
    static newImage(): Image;
    static newImageButton(): ImageButton;
    static newNavigation(): Navigation;
    static newNotification(): Notification;
    static newOpenLink(): OpenLink;
    static newSelectionInput(): SelectionInput;
    static newSuggestions(): Suggestions;
    static newTextButton(): TextButton;
    static newTextInput(): TextInput;
    static newTextParagraph(): TextParagraph;
    static newUniversalActionResponseBuilder(): UniversalActionResponseBuilder;
    static get ComposeEmailType(): typeof ComposeEmailType;
    static get Icon(): typeof Icon;
    static get ImageStyle(): typeof ImageStyle;
    static get LoadIndicator(): typeof LoadIndicator;
    static get NotificationType(): typeof NotificationType;
    static get OnClose(): typeof OnClose;
    static get OpenAs(): typeof OpenAs;
    static get SelectionInputType(): typeof SelectionInputType;
    static get TextButtonStyle(): typeof TextButtonStyle;
    static get ContentType(): typeof ContentType;
    static get UpdateDraftBodyType(): typeof UpdateDraftBodyType;
}
